services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    environment:
      - WIREMOCK_OPTIONS=--global-response-templating --verbose
